#pragma once
#include <iostream>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <queue>
#include <stack>
#include <string>
#include <deque>
#include <vector>
#include <map>
#include <tuple>
#include <iterator>
#include <cstdio>
#include <malloc.h>